# TD($\lambda$)

In [1]:
import numpy as np
import pandas as pd

In [2]:
def computeTD1(prob, R):
    return prob*(R[0] + R[2]) + (1-prob)*(R[1] + R[3]) + R[4] + R[5] + R[6]

def computeEk(k, prob, V, R):
    if k == 1:
        return prob*(R[0] + V[1]) + (1-prob)*(R[1] + V[2])
    elif k == 2:
        return prob*(R[0] + R[2] + V[3]) + (1-prob)*(R[1] + R[3] + V[3])
    else:
        Ek = prob*(R[0] + R[2]) + (1-prob)*(R[1] + R[3])
        for i in range(4, 4 + k-2):
            Ek += R[i]
        Ek += V[i]
        return Ek

## Example 1

In [3]:
prob = 0.81
valueEstimates = [0.0,4.0,25.7,0.0,20.1,12.2,0.0] 
rewards = [7.9,-5.1,2.5,-7.2,9.0,0.0,1.6]

In [4]:
td1 = computeTD1(prob, rewards)
E = [computeEk(i, prob, valueEstimates, rewards) for i in range(1, 1 + 5)]

In [5]:
td1, E

(16.687, [13.553, 6.0870000000000015, 35.187000000000005, 27.287, 16.687])

In [6]:
E.reverse()
coef = [x - td1 for x in E]
coef

[0.0, 10.599999999999998, 18.500000000000004, -10.6, -3.1340000000000003]

In [7]:
np.roots(coef)

array([-2.14692153,  0.6227695 , -0.22113099])

## Example 2

In [8]:
prob = 0.22
valueEstimates = [0.0,-5.2,0.0,25.4,10.6,9.2,12.3] 
rewards = [-2.4,0.8,4.0,2.5,8.6,-6.4,6.1]

In [12]:
td1 = computeTD1(prob, rewards)
E = [computeEk(i, prob, valueEstimates, rewards) for i in range(1, 1 + 5)]
td1, E

(11.225999999999999,
 [-1.0479999999999998, 28.326, 22.125999999999998, 14.325999999999999, 23.526])

In [10]:
E.reverse()
coef = [x - td1 for x in E]
coef

[12.3, 3.0999999999999996, 10.899999999999999, 17.1, -12.274]

In [11]:
np.roots(coef)

array([-1.16015001+0.j       ,  0.20622303+1.3010633j,
        0.20622303-1.3010633j,  0.49567142+0.j       ])

## Example 3

In [13]:
prob = 0.64
valueEstimates = [0.0,4.9,7.8,-2.3,25.5,-10.2,-6.5] 
rewards = [-2.4,9.6,-7.8,0.1,3.4,-2.1,7.9]

In [14]:
td1 = computeTD1(prob, rewards)
E = [computeEk(i, prob, valueEstimates, rewards) for i in range(1, 1 + 5)]
td1, E

(6.164, [7.864, -5.336, 25.864, -11.936, -0.3360000000000003])

In [15]:
E.reverse()
coef = [x - td1 for x in E]
coef

[-6.5, -18.1, 19.700000000000003, -11.5, 1.7000000000000002]

In [16]:
np.roots(coef)

array([-3.72950282+0.j        ,  0.36969234+0.45229758j,
        0.36969234-0.45229758j,  0.20550276+0.j        ])